services:
  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ackend

  mongod:
    image: mongo:latest
    container_name: down2mark_mongod_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/d
      - ./mongo-init.js:/docker-entrypoint-initd.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

volumes:
  mongo_data:
  redis_data:

networks:
  ackend:
    driver: ridge
